/**
 * Writes supabase/seed.sql from lib/content.ts, so the database starts with
 * exactly what the site shows today. Re-running the seed resets this site's
 * content (bookings are never touched).
 *
 *   node --experimental-strip-types scripts/seed-sql.mts
 */
import { writeFileSync } from "node:fs";
import { catchOfDay, closedOverride, faqs, menu, seasons } from "../lib/content.ts";

const SITE = "konoba";
const q = (v: string | null | undefined) => (v == null ? "null" : `'${v.replace(/'/g, "''")}'`);
const b = (v: boolean | undefined) => (v ? "true" : "false");

const out: string[] = [
  "-- Generated by scripts/seed-sql.mts from lib/content.ts. Do not edit by hand.",
  "begin;",
  ...["menu_items", "menu_categories", "opening_hours", "seasons", "faqs", "catch_items", "site_settings"].map(
    (t) => `delete from ${t} where site_id = '${SITE}';`,
  ),
];

menu.forEach((c, ci) => {
  out.push(
    `insert into menu_categories (site_id, slug, name_hr, name_en, name_de, photo, sort) values ('${SITE}', ${q(c.id)}, ${q(c.name.hr)}, ${q(c.name.en)}, ${q(c.name.de)}, ${q(c.photo)}, ${ci});`,
  );
  c.items.forEach((i, ii) => {
    out.push(
      `insert into menu_items (site_id, category_id, name_hr, name_en, name_de, description_hr, description_en, description_de, price, tags, signature, image, sort) ` +
        `select '${SITE}', id, ${q(i.name.hr)}, ${q(i.name.en)}, ${q(i.name.de)}, ${q(i.desc.hr)}, ${q(i.desc.en)}, ${q(i.desc.de)}, ${q(i.price)}, ` +
        `array[${i.tags.map(q).join(", ")}]::text[], ${b(i.signature)}, ${q(i.photo)}, ${ii} from menu_categories where site_id = '${SITE}' and slug = ${q(c.id)};`,
    );
  });
});

seasons.forEach((s, si) => {
  out.push(
    `insert into seasons (site_id, id, name_hr, name_en, name_de, from_md, to_md, sort) values ('${SITE}', ${q(s.id)}, ${q(s.name.hr)}, ${q(s.name.en)}, ${q(s.name.de)}, ${q(s.from)}, ${q(s.to)}, ${si});`,
  );
  for (let d = 0; d < 7; d++) {
    const h = s.hours[d];
    out.push(`insert into opening_hours (site_id, season_id, weekday, opens, closes) values ('${SITE}', ${q(s.id)}, ${d}, ${q(h?.[0])}, ${q(h?.[1])});`);
  }
});

faqs.forEach((f, i) => {
  out.push(
    `insert into faqs (site_id, question_hr, question_en, question_de, answer_hr, answer_en, answer_de, sort) values ('${SITE}', ${q(f.q.hr)}, ${q(f.q.en)}, ${q(f.q.de)}, ${q(f.a.hr)}, ${q(f.a.en)}, ${q(f.a.de)}, ${i});`,
  );
});

catchOfDay.items.forEach((c, i) => {
  out.push(
    `insert into catch_items (site_id, name_hr, name_en, name_de, how_hr, how_en, how_de, price, sold_out, photo, sort) values ('${SITE}', ${q(c.name.hr)}, ${q(c.name.en)}, ${q(c.name.de)}, ${q(c.how.hr)}, ${q(c.how.en)}, ${q(c.how.de)}, ${q(c.price)}, ${b(c.soldOut)}, ${q(c.photo)}, ${i});`,
  );
});

out.push(
  `insert into site_settings (site_id, catch_headline_hr, catch_headline_en, catch_headline_de, catch_note_hr, catch_note_en, catch_note_de, catch_by, catch_updated_at, closed_override, closed_note_hr, closed_note_en, closed_note_de) values ('${SITE}', ` +
    [catchOfDay.headline.hr, catchOfDay.headline.en, catchOfDay.headline.de, catchOfDay.note.hr, catchOfDay.note.en, catchOfDay.note.de, catchOfDay.by, catchOfDay.updatedAt]
      .map(q)
      .join(", ") +
    `, ${b(closedOverride.active)}, ${q(closedOverride.note.hr)}, ${q(closedOverride.note.en)}, ${q(closedOverride.note.de)});`,
  "commit;",
  "",
);

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), out.join("\n"));
console.log(`supabase/seed.sql: ${out.length} lines`);
